Repository HetviSoni/code-fraggers, pull requests merged in 2022-10, with the labels that each got.

#5 I added hover and focus effect to buttons
  src/components/header/header.css
Labels: hacktoberfest

#8 Update README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#11 contributing.md file added
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#13 Added Code of Conduct
  CODE_OF_CONDUCT.md
Labels: hacktoberfest, hacktoberfest-accepted

#18 added animation on homepage
  package-lock.json
  package.json
  src/components/body/boy.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#30 Improved Button design
  package-lock.json
  src/App.css
  src/components/body/button.js
  src/components/body/sub-container1.js
  src/components/body/sub-container2.js
  src/styles/header.css
  src/styles/subcontainer.css
Labels: hacktoberfest, hacktoberfest-accepted

#35 routes to signup page and sign in page
  package-lock.json
  package.json
  src/App.js
  src/components/body/homepage.js
  src/components/header/header.js
  src/components/signIn/login.js
  src/components/signUp/SignupForm.js
  src/styles/login.css
  src/styles/signup.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#50 Fixed Readme Streched Logo and Upscaled it!
  README.md
  src/assets/logohorizontal.png
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#53 Updated the sign-up and sign-in pages
  src/App.js
  src/components/signIn/login.js
  src/components/signUp/SignupForm.js
  src/styles/login.css
  src/styles/signup.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
